"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

export type Quadrant = "adopt" | "trial" | "assess" | "hold"

export interface TechItem {
  id: string
  name: string
  quadrant: Quadrant
  description: string
  isNew?: boolean
  githubLink?: string
  stars?: number
  contributors?: number
  daysSinceLastRelease?: number
  relatedTo?: string[]
  category?: string
}

interface TechRadarContextType {
  items: TechItem[]
  filteredItems: TechItem[]
  addItem: (item: Omit<TechItem, "id">) => void
  removeItem: (id: string) => void
  updateItem: (id: string, item: Partial<TechItem>) => void
  selectedItem: TechItem | null
  setSelectedItem: (item: TechItem | null) => void
  filteredQuadrant: Quadrant | "all"
  setFilteredQuadrant: (quadrant: Quadrant | "all") => void
  filteredCategories: string[]
  setFilteredCategories: (category: string[]) => void
  searchTerm: string
  setSearchTerm: (term: string) => void
  showModal: boolean
  setShowModal: (show: boolean) => void
  showRelations: boolean
  setShowRelations: (show: boolean) => void
  starsRange: [number, number]
  setStarsRange: (range: [number, number]) => void
  contributorsRange: [number, number]
  setContributorsRange: (range: [number, number]) => void
  daysRange: [number, number]
  setDaysRange: (range: [number, number]) => void
  searchIn: "all" | "name" | "description"
  setSearchIn: (searchIn: "all" | "name" | "description") => void
  viewMode: "radar" | "table"
  setViewMode: (mode: "radar" | "table") => void
}

// Helper function to assign a category to each item
const assignCategory = (name: string): string => {
  // Languages
  if (
    [
      "TypeScript",
      "JavaScript",
      "Dart",
      "Swift",
      "Kotlin",
      "C#",
      "Objective-C",
      "Elm",
      "ReScript",
      "ClojureScript",
      "PureScript",
    ].includes(name)
  ) {
    return "languages"
  }

  // Frameworks
  if (["React", "Vue.js", "Angular", "Svelte", "Solid.js", "Preact", "Alpine.js", "HTMX"].includes(name)) {
    return "frameworks"
  }

  // Meta-frameworks
  if (["Next.js", "Nuxt.js", "Remix", "Astro", "Gatsby", "SvelteKit", "Blazor"].includes(name)) {
    return "meta-frameworks"
  }

  // UI Libraries
  if (
    [
      "Tailwind CSS",
      "Material UI",
      "Chakra UI",
      "Shadcn UI",
      "Bootstrap",
      "Ant Design",
      "XAML",
      "SwiftUI",
      "Jetpack Compose",
    ].includes(name)
  ) {
    return "ui-libraries"
  }

  // Form Libraries
  if (
    [
      "React Hook Form",
      "Formik",
      "React Final Form",
      "Vuelidate",
      "VeeValidate",
      "FormKit",
      "Angular Reactive Forms",
      "ngx-formly",
      "Zod",
      "Yup",
      "Vest",
      "Svelte Forms Lib",
      "Felte",
    ].includes(name)
  ) {
    return "form-libraries"
  }

  // Chart Libraries
  if (
    [
      "D3.js",
      "Chart.js",
      "Recharts",
      "Victory",
      "Nivo",
      "Visx",
      "ApexCharts",
      "Highcharts",
      "ECharts",
      "Plotly.js",
      "C3.js",
      "Vega",
      "Vega-Lite",
      "G2Plot",
      "Chartist",
    ].includes(name)
  ) {
    return "chart-libraries"
  }

  // Date Libraries
  if (
    [
      "date-fns",
      "Moment.js",
      "Day.js",
      "Luxon",
      "js-joda",
      "date-io",
      "React Datepicker",
      "Flatpickr",
      "FullCalendar",
      "React Big Calendar",
      "Vue Calendar",
      "Angular Material Datepicker",
    ].includes(name)
  ) {
    return "date-libraries"
  }

  // Testing
  if (
    [
      "Cypress",
      "Playwright",
      "Jest",
      "Testing Library",
      "Vitest",
      "Selenium",
      "Puppeteer",
      "WebdriverIO",
      "Mocha",
      "Jasmine",
      "Karma",
      "Appium",
      "Postman",
      "k6",
    ].includes(name)
  ) {
    return "testing"
  }

  // State Management
  if (["Redux", "React Query", "Zustand", "Jotai", "MobX"].includes(name)) {
    return "state-management"
  }

  // Build Tools
  if (["Vite", "Webpack", "Gulp"].includes(name)) {
    return "build-tools"
  }

  // Mobile
  if (["React Native", "Flutter"].includes(name)) {
    return "mobile"
  }

  // CMS
  if (
    [
      "Adobe Experience Manager",
      "Contentful",
      "Storyblok",
      "Sanity",
      "Prismic",
      "Strapi",
      "WordPress",
      "Drupal",
      "Ghost",
      "Webflow",
      "Payload CMS",
      "Directus",
      "Netlify CMS",
      "Tina CMS",
    ].includes(name)
  ) {
    return "cms"
  }

  return "other"
}

// Convert the existing items to remove ring property and add category
const defaultItems: TechItem[] = [
  // Frameworks
  {
    id: "1",
    name: "React",
    quadrant: "adopt",
    description: "A JavaScript library for building user interfaces with a component-based architecture",
    isNew: false,
    githubLink: "https://github.com/facebook/react",
    stars: 212000,
    contributors: 1683,
    daysSinceLastRelease: 45,
    relatedTo: ["9", "13", "16", "18", "22", "23", "25", "29", "30", "33"],
    category: "frameworks",
  },
  {
    id: "2",
    name: "Vue.js",
    quadrant: "adopt",
    description: "Progressive JavaScript framework for building user interfaces with an approachable learning curve",
    isNew: false,
    githubLink: "https://github.com/vuejs/vue",
    stars: 203000,
    contributors: 398,
    daysSinceLastRelease: 62,
    relatedTo: ["10", "20", "29", "30"],
    category: "frameworks",
  },
  {
    id: "3",
    name: "Angular",
    quadrant: "trial",
    description: "Platform and framework for building single-page client applications using HTML and TypeScript",
    isNew: false,
    githubLink: "https://github.com/angular/angular",
    stars: 89000,
    contributors: 1456,
    daysSinceLastRelease: 30,
    relatedTo: ["21", "29", "31"],
    category: "frameworks",
  },
  {
    id: "4",
    name: "Svelte",
    quadrant: "trial",
    description: "Compiler-based framework that eliminates the virtual DOM for faster runtime performance",
    isNew: true,
    githubLink: "https://github.com/sveltejs/svelte",
    stars: 72000,
    contributors: 587,
    daysSinceLastRelease: 15,
    relatedTo: ["14", "29", "30"],
    category: "frameworks",
  },
  {
    id: "5",
    name: "Solid.js",
    quadrant: "assess",
    description: "Declarative, efficient, and flexible JavaScript library for building user interfaces",
    isNew: true,
    githubLink: "https://github.com/solidjs/solid",
    stars: 28000,
    contributors: 178,
    daysSinceLastRelease: 7,
    relatedTo: ["24", "29"],
    category: "frameworks",
  },
  {
    id: "6",
    name: "Preact",
    quadrant: "assess",
    description: "Fast 3kB alternative to React with the same modern API",
    isNew: false,
    githubLink: "https://github.com/preactjs/preact",
    stars: 34000,
    contributors: 289,
    daysSinceLastRelease: 90,
    relatedTo: ["1", "24", "29"],
    category: "frameworks",
  },
  {
    id: "7",
    name: "jQuery",
    quadrant: "hold",
    description: "Fast, small, and feature-rich JavaScript library for DOM manipulation",
    isNew: false,
    githubLink: "https://github.com/jquery/jquery",
    stars: 57000,
    contributors: 285,
    daysSinceLastRelease: 180,
    relatedTo: ["19", "28"],
    category: "frameworks",
  },
  {
    id: "8",
    name: "Backbone.js",
    quadrant: "hold",
    description: "Gives structure to web applications by providing models with key-value binding and custom events",
    isNew: false,
    githubLink: "https://github.com/jashkenas/backbone",
    stars: 27000,
    contributors: 302,
    daysSinceLastRelease: 365,
    relatedTo: ["7", "28"],
    category: "frameworks",
  },
  {
    id: "9",
    name: "Next.js",
    quadrant: "adopt",
    description:
      "React framework for production with hybrid static & server rendering, TypeScript support, and route pre-fetching",
    isNew: false,
    githubLink: "https://github.com/vercel/next.js",
    stars: 112000,
    contributors: 2300,
    daysSinceLastRelease: 5,
    relatedTo: ["1", "15", "18", "22", "29", "30"],
    category: "meta-frameworks",
  },
  {
    id: "10",
    name: "Nuxt.js",
    quadrant: "adopt",
    description: "Intuitive Vue framework for building modern web applications with server-side rendering",
    isNew: false,
    githubLink: "https://github.com/nuxt/nuxt",
    stars: 47000,
    contributors: 418,
    daysSinceLastRelease: 14,
    relatedTo: ["2", "15", "29", "30"],
    category: "meta-frameworks",
  },
  {
    id: "11",
    name: "Remix",
    quadrant: "trial",
    description: "Full stack web framework focused on web standards and modern UX",
    isNew: true,
    githubLink: "https://github.com/remix-run/remix",
    stars: 24000,
    contributors: 245,
    daysSinceLastRelease: 8,
    relatedTo: ["1", "15", "29", "30"],
    category: "meta-frameworks",
  },
  {
    id: "12",
    name: "Astro",
    quadrant: "trial",
    description: "All-in-one web framework for building fast, content-focused websites",
    isNew: true,
    githubLink: "https://github.com/withastro/astro",
    stars: 34000,
    contributors: 378,
    daysSinceLastRelease: 3,
    relatedTo: ["1", "2", "4", "15", "24", "29"],
    category: "meta-frameworks",
  },
  {
    id: "13",
    name: "Gatsby",
    quadrant: "assess",
    description: "React-based framework for building websites and apps with excellent performance",
    isNew: false,
    githubLink: "https://github.com/gatsbyjs/gatsby",
    stars: 54000,
    contributors: 3800,
    daysSinceLastRelease: 45,
    relatedTo: ["1", "15", "29", "30"],
    category: "meta-frameworks",
  },
  {
    id: "14",
    name: "SvelteKit",
    quadrant: "assess",
    description: "Framework for building web applications of all sizes with Svelte",
    isNew: true,
    githubLink: "https://github.com/sveltejs/kit",
    stars: 15000,
    contributors: 320,
    daysSinceLastRelease: 10,
    relatedTo: ["4", "15", "24", "29"],
    category: "meta-frameworks",
  },
  {
    id: "15",
    name: "Tailwind CSS",
    quadrant: "adopt",
    description: "Utility-first CSS framework for rapidly building custom user interfaces",
    isNew: false,
    githubLink: "https://github.com/tailwindlabs/tailwindcss",
    stars: 71000,
    contributors: 248,
    daysSinceLastRelease: 30,
    relatedTo: ["9", "10", "11", "12", "13", "14", "18", "26"],
    category: "ui-libraries",
  },
  {
    id: "16",
    name: "Material UI",
    quadrant: "adopt",
    description: "React components for faster and easier web development following Material Design",
    isNew: false,
    githubLink: "https://github.com/mui/material-ui",
    stars: 87000,
    contributors: 2700,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "9", "29", "30"],
    category: "ui-libraries",
  },
  {
    id: "17",
    name: "Chakra UI",
    quadrant: "trial",
    description: "Simple, modular and accessible component library for React applications",
    isNew: false,
    githubLink: "https://github.com/chakra-ui/chakra-ui",
    stars: 33000,
    contributors: 580,
    daysSinceLastRelease: 21,
    relatedTo: ["1", "9", "29", "30"],
    category: "ui-libraries",
  },
  {
    id: "18",
    name: "Shadcn UI",
    quadrant: "trial",
    description: "Re-usable components built using Radix UI and Tailwind CSS",
    isNew: true,
    githubLink: "https://github.com/shadcn-ui/ui",
    stars: 45000,
    contributors: 180,
    daysSinceLastRelease: 5,
    relatedTo: ["1", "9", "15", "29"],
    category: "ui-libraries",
  },
  {
    id: "19",
    name: "Bootstrap",
    quadrant: "assess",
    description: "CSS framework directed at responsive, mobile-first front-end web development",
    isNew: false,
    githubLink: "https://github.com/twbs/bootstrap",
    stars: 164000,
    contributors: 1200,
    daysSinceLastRelease: 60,
    relatedTo: ["7", "28"],
    category: "ui-libraries",
  },
  {
    id: "20",
    name: "Ant Design",
    quadrant: "assess",
    description: "Enterprise-class UI design language and React UI library",
    isNew: false,
    githubLink: "https://github.com/ant-design/ant-design",
    stars: 87000,
    contributors: 1800,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "2", "9", "29", "30"],
    category: "ui-libraries",
  },
  {
    id: "21",
    name: "Redux",
    quadrant: "adopt",
    description: "Predictable state container for JavaScript apps",
    isNew: false,
    githubLink: "https://github.com/reduxjs/redux",
    stars: 59000,
    contributors: 910,
    daysSinceLastRelease: 120,
    relatedTo: ["1", "3", "9", "29"],
    category: "state-management",
  },
  {
    id: "22",
    name: "React Query",
    quadrant: "adopt",
    description: "Data-fetching and state management library for React applications",
    isNew: false,
    githubLink: "https://github.com/tanstack/query",
    stars: 35000,
    contributors: 480,
    daysSinceLastRelease: 15,
    relatedTo: ["1", "9", "29"],
    category: "state-management",
  },
  {
    id: "23",
    name: "Zustand",
    quadrant: "trial",
    description: "Small, fast and scalable bearbones state-management solution",
    isNew: true,
    githubLink: "https://github.com/pmndrs/zustand",
    stars: 34000,
    contributors: 210,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "9", "29"],
    category: "state-management",
  },
  {
    id: "24",
    name: "Vite",
    quadrant: "trial",
    description: "Next generation frontend tooling with fast HMR and optimized build",
    isNew: true,
    githubLink: "https://github.com/vitejs/vite",
    stars: 58000,
    contributors: 780,
    daysSinceLastRelease: 3,
    relatedTo: ["1", "2", "4", "5", "6", "12", "14", "29"],
    category: "build-tools",
  },
  {
    id: "25",
    name: "Jotai",
    quadrant: "assess",
    description: "Primitive and flexible state management for React",
    isNew: true,
    githubLink: "https://github.com/pmndrs/jotai",
    stars: 14000,
    contributors: 120,
    daysSinceLastRelease: 10,
    relatedTo: ["1", "9", "29"],
    category: "state-management",
  },
  {
    id: "26",
    name: "Webpack",
    quadrant: "assess",
    description: "Static module bundler for modern JavaScript applications",
    isNew: false,
    githubLink: "https://github.com/webpack/webpack",
    stars: 62000,
    contributors: 780,
    daysSinceLastRelease: 45,
    relatedTo: ["1", "2", "3", "9", "10", "15", "29"],
    category: "build-tools",
  },
  {
    id: "27",
    name: "MobX",
    quadrant: "hold",
    description: "Simple, scalable state management",
    isNew: false,
    githubLink: "https://github.com/mobxjs/mobx",
    stars: 26000,
    contributors: 240,
    daysSinceLastRelease: 90,
    relatedTo: ["1", "29"],
    category: "state-management",
  },
  {
    id: "28",
    name: "Gulp",
    quadrant: "hold",
    description: "Toolkit to automate & enhance your workflow",
    isNew: false,
    githubLink: "https://github.com/gulpjs/gulp",
    stars: 32000,
    contributors: 320,
    daysSinceLastRelease: 180,
    relatedTo: ["7", "8", "19"],
    category: "build-tools",
  },
  {
    id: "29",
    name: "TypeScript",
    quadrant: "adopt",
    description: "Typed superset of JavaScript that compiles to plain JavaScript",
    isNew: false,
    githubLink: "https://github.com/microsoft/TypeScript",
    stars: 92000,
    contributors: 870,
    daysSinceLastRelease: 14,
    relatedTo: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "16",
      "17",
      "18",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "30",
      "31",
      "32",
      "33",
      "34",
    ],
    category: "languages",
  },
  {
    id: "30",
    name: "Storybook",
    quadrant: "adopt",
    description: "Frontend workshop for building UI components and pages in isolation",
    isNew: false,
    githubLink: "https://github.com/storybookjs/storybook",
    stars: 78000,
    contributors: 1500,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "2", "3", "4", "9", "10", "11", "13", "16", "17", "20", "29"],
    category: "ui-libraries",
  },
  {
    id: "31",
    name: "Cypress",
    quadrant: "trial",
    description: "JavaScript end-to-end testing framework",
    isNew: false,
    githubLink: "https://github.com/cypress-io/cypress",
    stars: 44000,
    contributors: 410,
    daysSinceLastRelease: 21,
    relatedTo: ["1", "2", "3", "4", "9", "10", "29", "32"],
    category: "testing",
  },
  {
    id: "32",
    name: "Playwright",
    quadrant: "trial",
    description: "Framework for web testing and automation",
    isNew: true,
    githubLink: "https://github.com/microsoft/playwright",
    stars: 54000,
    contributors: 520,
    daysSinceLastRelease: 5,
    relatedTo: ["1", "2", "3", "4", "9", "10", "29", "31"],
    category: "testing",
  },
  {
    id: "33",
    name: "Framer Motion",
    quadrant: "assess",
    description: "Production-ready motion library for React",
    isNew: true,
    githubLink: "https://github.com/framer/motion",
    stars: 19000,
    contributors: 110,
    daysSinceLastRelease: 30,
    relatedTo: ["1", "9", "29"],
    category: "ui-libraries",
  },
  {
    id: "34",
    name: "Three.js",
    quadrant: "assess",
    description: "JavaScript 3D library for creating 3D graphics in the browser",
    isNew: false,
    githubLink: "https://github.com/mrdoob/three.js",
    stars: 94000,
    contributors: 1700,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "2", "9", "10", "29"],
    category: "ui-libraries",
  },

  // Frontend languages
  {
    id: "35",
    name: "JavaScript",
    quadrant: "adopt",
    description: "High-level, interpreted programming language that is the foundation of web development",
    isNew: false,
    githubLink: "https://github.com/tc39/ecma262",
    stars: 14000,
    contributors: 150,
    daysSinceLastRelease: 90,
    relatedTo: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "29"],
    category: "languages",
  },
  {
    id: "36",
    name: "Dart",
    quadrant: "trial",
    description: "Client-optimized language for fast apps on any platform, primarily used with Flutter",
    isNew: false,
    githubLink: "https://github.com/dart-lang/sdk",
    stars: 8900,
    contributors: 580,
    daysSinceLastRelease: 14,
    relatedTo: ["37"],
    category: "languages",
  },
  {
    id: "37",
    name: "Flutter",
    quadrant: "trial",
    description: "Google's UI toolkit for building natively compiled applications across mobile, web, and desktop",
    isNew: false,
    githubLink: "https://github.com/flutter/flutter",
    stars: 152000,
    contributors: 970,
    daysSinceLastRelease: 7,
    relatedTo: ["36"],
    category: "mobile",
  },
  {
    id: "38",
    name: "Swift",
    quadrant: "adopt",
    description: "Powerful and intuitive programming language for iOS, macOS, and other Apple platforms",
    isNew: false,
    githubLink: "https://github.com/apple/swift",
    stars: 63000,
    contributors: 1100,
    daysSinceLastRelease: 30,
    relatedTo: ["40", "44"],
    category: "languages",
  },
  {
    id: "39",
    name: "Kotlin",
    quadrant: "adopt",
    description: "Modern programming language that makes developers happier, primarily used for Android development",
    isNew: false,
    githubLink: "https://github.com/JetBrains/kotlin",
    stars: 45000,
    contributors: 520,
    daysSinceLastRelease: 21,
    relatedTo: ["41"],
    category: "languages",
  },
  {
    id: "40",
    name: "SwiftUI",
    quadrant: "trial",
    description: "Declarative UI framework for building user interfaces across all Apple platforms",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 180,
    relatedTo: ["38"],
    category: "ui-libraries",
  },
  {
    id: "41",
    name: "Jetpack Compose",
    quadrant: "trial",
    description: "Modern toolkit for building native Android UI with a declarative approach",
    isNew: true,
    githubLink: "https://github.com/androidx/androidx",
    stars: 4200,
    contributors: 320,
    daysSinceLastRelease: 14,
    relatedTo: ["39"],
    category: "ui-libraries",
  },
  {
    id: "42",
    name: "C#",
    quadrant: "adopt",
    description: "Modern, object-oriented programming language developed by Microsoft for the .NET platform",
    isNew: false,
    githubLink: "https://github.com/dotnet/csharplang",
    stars: 9800,
    contributors: 210,
    daysSinceLastRelease: 60,
    relatedTo: ["43", "45"],
    category: "languages",
  },
  {
    id: "43",
    name: "XAML",
    quadrant: "trial",
    description: "Declarative markup language used for initializing structured values and objects in .NET",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 365,
    relatedTo: ["42", "45"],
    category: "ui-libraries",
  },
  {
    id: "44",
    name: "Objective-C",
    quadrant: "hold",
    description:
      "General-purpose, object-oriented programming language used for iOS and macOS development before Swift",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 730,
    relatedTo: ["38", "40"],
    category: "languages",
  },
  {
    id: "45",
    name: "WPF",
    quadrant: "assess",
    description: "Windows Presentation Foundation, a UI framework for building Windows desktop applications",
    isNew: false,
    githubLink: "https://github.com/dotnet/wpf",
    stars: 5800,
    contributors: 130,
    daysSinceLastRelease: 90,
    relatedTo: ["42", "43"],
    category: "ui-libraries",
  },
  {
    id: "46",
    name: "Elm",
    quadrant: "assess",
    description: "A functional language that compiles to JavaScript, known for its reliability and maintainability",
    isNew: false,
    githubLink: "https://github.com/elm/compiler",
    stars: 7200,
    contributors: 110,
    daysSinceLastRelease: 180,
    relatedTo: ["29", "35"],
    category: "languages",
  },
  {
    id: "47",
    name: "ReScript",
    quadrant: "assess",
    description: "A robustly typed language that compiles to efficient JavaScript, formerly known as ReasonML",
    isNew: true,
    githubLink: "https://github.com/rescript-lang/rescript-compiler",
    stars: 5400,
    contributors: 90,
    daysSinceLastRelease: 45,
    relatedTo: ["1", "29", "35"],
    category: "languages",
  },
  {
    id: "48",
    name: "ClojureScript",
    quadrant: "assess",
    description:
      "Compiler for Clojure that targets JavaScript, bringing functional programming to frontend development",
    isNew: false,
    githubLink: "https://github.com/clojure/clojurescript",
    stars: 8900,
    contributors: 320,
    daysSinceLastRelease: 60,
    relatedTo: ["29", "35"],
    category: "languages",
  },
  {
    id: "49",
    name: "PureScript",
    quadrant: "assess",
    description: "A strongly-typed functional programming language that compiles to JavaScript",
    isNew: false,
    githubLink: "https://github.com/purescript/purescript",
    stars: 7800,
    contributors: 210,
    daysSinceLastRelease: 90,
    relatedTo: ["29", "35", "46"],
    category: "languages",
  },
  {
    id: "50",
    name: "React Native",
    quadrant: "adopt",
    description: "Framework for building native mobile applications using React and JavaScript",
    isNew: false,
    githubLink: "https://github.com/facebook/react-native",
    stars: 110000,
    contributors: 2800,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "29", "35"],
    category: "mobile",
  },
  {
    id: "51",
    name: "Blazor",
    quadrant: "trial",
    description: "Framework for building interactive web UIs using C# instead of JavaScript",
    isNew: true,
    githubLink: "https://github.com/dotnet/aspnetcore",
    stars: 31000,
    contributors: 1900,
    daysSinceLastRelease: 30,
    relatedTo: ["42"],
    category: "frameworks",
  },
  {
    id: "52",
    name: "HTMX",
    quadrant: "trial",
    description: "High-power tools for HTML, allowing for AJAX, CSS transitions, and WebSockets without JavaScript",
    isNew: true,
    githubLink: "https://github.com/bigskysoftware/htmx",
    stars: 21000,
    contributors: 180,
    daysSinceLastRelease: 7,
    relatedTo: ["35"],
    category: "frameworks",
  },
  {
    id: "53",
    name: "Alpine.js",
    quadrant: "trial",
    description:
      "Minimal framework for composing JavaScript behavior in your markup with a reactive and declarative nature",
    isNew: true,
    githubLink: "https://github.com/alpinejs/alpine",
    stars: 24000,
    contributors: 120,
    daysSinceLastRelease: 30,
    relatedTo: ["35", "52"],
    category: "frameworks",
  },

  // Additional Testing Tools
  {
    id: "54",
    name: "Jest",
    quadrant: "adopt",
    description: "Delightful JavaScript testing framework with a focus on simplicity",
    isNew: false,
    githubLink: "https://github.com/facebook/jest",
    stars: 41000,
    contributors: 1350,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "29", "35", "55", "56"],
    category: "testing",
  },
  {
    id: "55",
    name: "Testing Library",
    quadrant: "adopt",
    description: "Simple and complete testing utilities that encourage good testing practices",
    isNew: false,
    githubLink: "https://github.com/testing-library/react-testing-library",
    stars: 17800,
    contributors: 320,
    daysSinceLastRelease: 30,
    relatedTo: ["1", "29", "35", "54"],
    category: "testing",
  },
  {
    id: "56",
    name: "Vitest",
    quadrant: "trial",
    description: "Next generation testing framework powered by Vite",
    isNew: true,
    githubLink: "https://github.com/vitest-dev/vitest",
    stars: 9800,
    contributors: 420,
    daysSinceLastRelease: 5,
    relatedTo: ["24", "54", "55"],
    category: "testing",
  },
  {
    id: "57",
    name: "Selenium",
    quadrant: "adopt",
    description: "Browser automation tool and WebDriver implementation",
    isNew: false,
    githubLink: "https://github.com/SeleniumHQ/selenium",
    stars: 26000,
    contributors: 820,
    daysSinceLastRelease: 45,
    relatedTo: ["31", "32", "58"],
    category: "testing",
  },
  {
    id: "58",
    name: "Puppeteer",
    quadrant: "trial",
    description: "Headless Chrome Node.js API for browser automation",
    isNew: false,
    githubLink: "https://github.com/puppeteer/puppeteer",
    stars: 82000,
    contributors: 480,
    daysSinceLastRelease: 7,
    relatedTo: ["31", "32", "57"],
    category: "testing",
  },
  {
    id: "59",
    name: "WebdriverIO",
    quadrant: "trial",
    description: "Next-gen browser and mobile automation test framework for Node.js",
    isNew: false,
    githubLink: "https://github.com/webdriverio/webdriverio",
    stars: 7800,
    contributors: 380,
    daysSinceLastRelease: 3,
    relatedTo: ["31", "32", "57", "58"],
    category: "testing",
  },
  {
    id: "60",
    name: "Mocha",
    quadrant: "assess",
    description: "Feature-rich JavaScript test framework running on Node.js and in the browser",
    isNew: false,
    githubLink: "https://github.com/mochajs/mocha",
    stars: 21800,
    contributors: 520,
    daysSinceLastRelease: 90,
    relatedTo: ["35", "54", "61"],
    category: "testing",
  },
  {
    id: "61",
    name: "Jasmine",
    quadrant: "assess",
    description: "Behavior-Driven JavaScript testing framework",
    isNew: false,
    githubLink: "https://github.com/jasmine/jasmine",
    stars: 15200,
    contributors: 280,
    daysSinceLastRelease: 120,
    relatedTo: ["35", "54", "60"],
    category: "testing",
  },
  {
    id: "62",
    name: "Karma",
    quadrant: "hold",
    description: "Test runner that runs tests in real browsers",
    isNew: false,
    githubLink: "https://github.com/karma-runner/karma",
    stars: 11400,
    contributors: 270,
    daysSinceLastRelease: 180,
    relatedTo: ["35", "54", "60", "61"],
    category: "testing",
  },
  {
    id: "63",
    name: "Appium",
    quadrant: "trial",
    description: "Automation framework for mobile apps testing",
    isNew: false,
    githubLink: "https://github.com/appium/appium",
    stars: 16500,
    contributors: 420,
    daysSinceLastRelease: 30,
    relatedTo: ["37", "50", "57"],
    category: "testing",
  },
  {
    id: "64",
    name: "Postman",
    quadrant: "adopt",
    description: "API platform for building and using APIs with automated testing capabilities",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 14,
    relatedTo: [],
    category: "testing",
  },
  {
    id: "65",
    name: "k6",
    quadrant: "trial",
    description: "Modern load testing tool for developers and testers",
    isNew: true,
    githubLink: "https://github.com/grafana/k6",
    stars: 19800,
    contributors: 210,
    daysSinceLastRelease: 7,
    relatedTo: ["35"],
    category: "testing",
  },

  // CMS Systems
  {
    id: "66",
    name: "Adobe Experience Manager",
    quadrant: "adopt",
    description: "Enterprise-grade content management system for building websites, mobile apps, and forms",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 90,
    relatedTo: [],
    category: "cms",
  },
  {
    id: "67",
    name: "Contentful",
    quadrant: "adopt",
    description: "API-first content management platform to create, manage and publish content on any digital channel",
    isNew: false,
    githubLink: "https://github.com/contentful",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 7,
    relatedTo: ["68", "69", "70", "71"],
    category: "cms",
  },
  {
    id: "68",
    name: "Storyblok",
    quadrant: "trial",
    description: "Headless CMS with a visual editor for creating content for websites, mobile apps, and e-commerce",
    isNew: true,
    githubLink: "https://github.com/storyblok",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 14,
    relatedTo: ["67", "69", "70", "71"],
    category: "cms",
  },
  {
    id: "69",
    name: "Sanity",
    quadrant: "trial",
    description: "Platform for structured content with real-time collaboration and customizable editing environment",
    isNew: true,
    githubLink: "https://github.com/sanity-io/sanity",
    stars: 4800,
    contributors: 120,
    daysSinceLastRelease: 3,
    relatedTo: ["67", "68", "70", "71"],
    category: "cms",
  },
  {
    id: "70",
    name: "Prismic",
    quadrant: "trial",
    description: "Headless CMS with a visual builder and customizable content types",
    isNew: false,
    githubLink: "https://github.com/prismicio",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 30,
    relatedTo: ["67", "68", "69", "71"],
    category: "cms",
  },
  {
    id: "71",
    name: "Strapi",
    quadrant: "trial",
    description: "Open-source headless CMS to build customizable APIs in hours instead of weeks",
    isNew: false,
    githubLink: "https://github.com/strapi/strapi",
    stars: 55000,
    contributors: 1200,
    daysSinceLastRelease: 7,
    relatedTo: ["67", "68", "69", "70"],
    category: "cms",
  },
  {
    id: "72",
    name: "WordPress",
    quadrant: "adopt",
    description: "World's most popular CMS, powering over 40% of all websites on the internet",
    isNew: false,
    githubLink: "https://github.com/WordPress/WordPress",
    stars: 17800,
    contributors: 820,
    daysSinceLastRelease: 30,
    relatedTo: ["73"],
    category: "cms",
  },
  {
    id: "73",
    name: "Drupal",
    quadrant: "assess",
    description: "Open-source content management framework for building digital experiences",
    isNew: false,
    githubLink: "https://github.com/drupal/drupal",
    stars: 4200,
    contributors: 1100,
    daysSinceLastRelease: 45,
    relatedTo: ["72"],
    category: "cms",
  },
  {
    id: "74",
    name: "Ghost",
    quadrant: "assess",
    description: "Professional publishing platform built on a modern Node.js tech stack",
    isNew: false,
    githubLink: "https://github.com/TryGhost/Ghost",
    stars: 42000,
    contributors: 420,
    daysSinceLastRelease: 14,
    relatedTo: ["72"],
    category: "cms",
  },
  {
    id: "75",
    name: "Webflow",
    quadrant: "trial",
    description:
      "Visual web design platform that allows users to design, build, and launch responsive websites visually",
    isNew: false,
    githubLink: "",
    stars: 0,
    contributors: 0,
    daysSinceLastRelease: 30,
    relatedTo: [],
    category: "cms",
  },
  {
    id: "76",
    name: "Payload CMS",
    quadrant: "assess",
    description: "Headless CMS and application framework built with TypeScript, Node.js, React and MongoDB",
    isNew: true,
    githubLink: "https://github.com/payloadcms/payload",
    stars: 12800,
    contributors: 180,
    daysSinceLastRelease: 3,
    relatedTo: ["67", "68", "69", "70", "71"],
    category: "cms",
  },
  {
    id: "77",
    name: "Directus",
    quadrant: "assess",
    description: "Open-source headless CMS and API for managing database content",
    isNew: true,
    githubLink: "https://github.com/directus/directus",
    stars: 23000,
    contributors: 320,
    daysSinceLastRelease: 1,
    relatedTo: ["67", "68", "69", "70", "71", "76"],
    category: "cms",
  },
  {
    id: "78",
    name: "Netlify CMS",
    quadrant: "hold",
    description: "Git-based CMS for static site generators (now deprecated in favor of Decap CMS)",
    isNew: false,
    githubLink: "https://github.com/netlify/netlify-cms",
    stars: 16500,
    contributors: 420,
    daysSinceLastRelease: 365,
    relatedTo: ["79"],
    category: "cms",
  },
  {
    id: "79",
    name: "Tina CMS",
    quadrant: "trial",
    description: "Open-source headless CMS that lives in your Git repository",
    isNew: true,
    githubLink: "https://github.com/tinacms/tinacms",
    stars: 8900,
    contributors: 140,
    daysSinceLastRelease: 7,
    relatedTo: ["67", "68", "69", "70", "71", "78"],
    category: "cms",
  },

  // Form Libraries
  {
    id: "80",
    name: "React Hook Form",
    quadrant: "adopt",
    description: "Performant, flexible and extensible forms with easy-to-use validation for React",
    isNew: false,
    githubLink: "https://github.com/react-hook-form/react-hook-form",
    stars: 35800,
    contributors: 320,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "9", "29", "81", "82", "88", "89"],
    category: "form-libraries",
  },
  {
    id: "81",
    name: "Formik",
    quadrant: "adopt",
    description: "Build forms in React, without the tears",
    isNew: false,
    githubLink: "https://github.com/jaredpalmer/formik",
    stars: 32000,
    contributors: 420,
    daysSinceLastRelease: 180,
    relatedTo: ["1", "9", "29", "80", "88", "89"],
    category: "form-libraries",
  },
  {
    id: "82",
    name: "React Final Form",
    quadrant: "assess",
    description: "High performance subscription-based form state management for React",
    isNew: false,
    githubLink: "https://github.com/final-form/react-final-form",
    stars: 7200,
    contributors: 110,
    daysSinceLastRelease: 365,
    relatedTo: ["1", "9", "29", "80", "81"],
    category: "form-libraries",
  },
  {
    id: "83",
    name: "Vuelidate",
    quadrant: "adopt",
    description: "Simple, lightweight model-based validation for Vue.js",
    isNew: false,
    githubLink: "https://github.com/vuelidate/vuelidate",
    stars: 6800,
    contributors: 120,
    daysSinceLastRelease: 30,
    relatedTo: ["2", "10", "29", "84"],
    category: "form-libraries",
  },
  {
    id: "84",
    name: "VeeValidate",
    quadrant: "adopt",
    description: "Form validation for Vue.js",
    isNew: false,
    githubLink: "https://github.com/logaretm/vee-validate",
    stars: 9800,
    contributors: 180,
    daysSinceLastRelease: 14,
    relatedTo: ["2", "10", "29", "83"],
    category: "form-libraries",
  },
  {
    id: "85",
    name: "FormKit",
    quadrant: "trial",
    description: "Form building framework for Vue that simplifies form creation and validation",
    isNew: true,
    githubLink: "https://github.com/formkit/formkit",
    stars: 3200,
    contributors: 80,
    daysSinceLastRelease: 7,
    relatedTo: ["2", "10", "29", "83", "84"],
    category: "form-libraries",
  },
  {
    id: "86",
    name: "Angular Reactive Forms",
    quadrant: "adopt",
    description: "Angular's built-in reactive approach to handling form inputs and validation",
    isNew: false,
    githubLink: "https://github.com/angular/angular",
    stars: 89000,
    contributors: 1456,
    daysSinceLastRelease: 30,
    relatedTo: ["3", "29", "87"],
    category: "form-libraries",
  },
  {
    id: "87",
    name: "ngx-formly",
    quadrant: "trial",
    description: "Dynamic form library for Angular that simplifies complex form creation",
    isNew: false,
    githubLink: "https://github.com/ngx-formly/ngx-formly",
    stars: 3400,
    contributors: 120,
    daysSinceLastRelease: 14,
    relatedTo: ["3", "29", "86"],
    category: "form-libraries",
  },
  {
    id: "88",
    name: "Zod",
    quadrant: "adopt",
    description: "TypeScript-first schema validation with static type inference",
    isNew: true,
    githubLink: "https://github.com/colinhacks/zod",
    stars: 25800,
    contributors: 280,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "80", "81", "89", "90"],
    category: "form-libraries",
  },
  {
    id: "89",
    name: "Yup",
    quadrant: "adopt",
    description: "JavaScript schema builder for value parsing and validation",
    isNew: false,
    githubLink: "https://github.com/jquense/yup",
    stars: 20400,
    contributors: 180,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "80", "81", "88", "90"],
    category: "form-libraries",
  },
  {
    id: "90",
    name: "Vest",
    quadrant: "assess",
    description: "Declarative form validation framework for JavaScript",
    isNew: true,
    githubLink: "https://github.com/ealush/vest",
    stars: 2800,
    contributors: 40,
    daysSinceLastRelease: 14,
    relatedTo: ["29", "88", "89"],
    category: "form-libraries",
  },
  {
    id: "91",
    name: "Svelte Forms Lib",
    quadrant: "trial",
    description: "A lightweight library for managing forms in Svelte",
    isNew: true,
    githubLink: "https://github.com/tjinauyeung/svelte-forms-lib",
    stars: 780,
    contributors: 30,
    daysSinceLastRelease: 180,
    relatedTo: ["4", "14", "29", "92"],
    category: "form-libraries",
  },
  {
    id: "92",
    name: "Felte",
    quadrant: "trial",
    description: "An extensible form library for Svelte, with built-in validation",
    isNew: true,
    githubLink: "https://github.com/pablo-abc/felte",
    stars: 980,
    contributors: 25,
    daysSinceLastRelease: 30,
    relatedTo: ["4", "14", "29", "91"],
    category: "form-libraries",
  },

  // Chart Libraries
  {
    id: "93",
    name: "D3.js",
    quadrant: "adopt",
    description: "JavaScript library for producing dynamic, interactive data visualizations in web browsers",
    isNew: false,
    githubLink: "https://github.com/d3/d3",
    stars: 104000,
    contributors: 140,
    daysSinceLastRelease: 60,
    relatedTo: ["29", "35", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107"],
    category: "chart-libraries",
  },
  {
    id: "94",
    name: "Chart.js",
    quadrant: "adopt",
    description: "Simple yet flexible JavaScript charting for designers & developers",
    isNew: false,
    githubLink: "https://github.com/chartjs/Chart.js",
    stars: 60800,
    contributors: 380,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "35", "93"],
    category: "chart-libraries",
  },
  {
    id: "95",
    name: "Recharts",
    quadrant: "adopt",
    description: "Redefined chart library built with React and D3",
    isNew: false,
    githubLink: "https://github.com/recharts/recharts",
    stars: 20800,
    contributors: 280,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "9", "29", "93"],
    category: "chart-libraries",
  },
  {
    id: "96",
    name: "Victory",
    quadrant: "trial",
    description: "React components for modular charting and data visualization",
    isNew: false,
    githubLink: "https://github.com/FormidableLabs/victory",
    stars: 10200,
    contributors: 180,
    daysSinceLastRelease: 30,
    relatedTo: ["1", "9", "29", "93", "95"],
    category: "chart-libraries",
  },
  {
    id: "97",
    name: "Nivo",
    quadrant: "trial",
    description: "Rich set of dataviz components for React, built on top of D3 and Reactjs",
    isNew: false,
    githubLink: "https://github.com/plouc/nivo",
    stars: 11800,
    contributors: 140,
    daysSinceLastRelease: 7,
    relatedTo: ["1", "9", "29", "93", "95", "96"],
    category: "chart-libraries",
  },
  {
    id: "98",
    name: "Visx",
    quadrant: "trial",
    description: "Collection of reusable low-level visualization components from Airbnb",
    isNew: true,
    githubLink: "https://github.com/airbnb/visx",
    stars: 17800,
    contributors: 120,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "9", "29", "93", "95", "96", "97"],
    category: "chart-libraries",
  },
  {
    id: "99",
    name: "ApexCharts",
    quadrant: "adopt",
    description: "Modern charting library that helps developers to create beautiful and interactive visualizations",
    isNew: false,
    githubLink: "https://github.com/apexcharts/apexcharts.js",
    stars: 12800,
    contributors: 120,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "35", "93", "94"],
    category: "chart-libraries",
  },
  {
    id: "100",
    name: "Highcharts",
    quadrant: "adopt",
    description: "Interactive JavaScript charts for web pages",
    isNew: false,
    githubLink: "https://github.com/highcharts/highcharts",
    stars: 11200,
    contributors: 80,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "35", "93", "94", "99"],
    category: "chart-libraries",
  },
  {
    id: "101",
    name: "ECharts",
    quadrant: "adopt",
    description: "An open-source JavaScript visualization library from Apache",
    isNew: false,
    githubLink: "https://github.com/apache/echarts",
    stars: 55800,
    contributors: 180,
    daysSinceLastRelease: 14,
    relatedTo: ["29", "35", "93", "94", "99", "100"],
    category: "chart-libraries",
  },
  {
    id: "102",
    name: "Plotly.js",
    quadrant: "trial",
    description: "Open-source JavaScript charting library behind Plotly and Dash",
    isNew: false,
    githubLink: "https://github.com/plotly/plotly.js",
    stars: 15800,
    contributors: 140,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "35", "93", "94", "99", "100", "101"],
    category: "chart-libraries",
  },
  {
    id: "103",
    name: "C3.js",
    quadrant: "assess",
    description: "D3-based reusable chart library",
    isNew: false,
    githubLink: "https://github.com/c3js/c3",
    stars: 9800,
    contributors: 120,
    daysSinceLastRelease: 180,
    relatedTo: ["29", "35", "93"],
    category: "chart-libraries",
  },
  {
    id: "104",
    name: "Vega",
    quadrant: "assess",
    description:
      "Declarative visualization grammar for creating, saving, and sharing interactive visualization designs",
    isNew: false,
    githubLink: "https://github.com/vega/vega",
    stars: 10200,
    contributors: 80,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "35", "93", "105"],
    category: "chart-libraries",
  },
  {
    id: "105",
    name: "Vega-Lite",
    quadrant: "assess",
    description: "High-level grammar of interactive graphics built on Vega",
    isNew: false,
    githubLink: "https://github.com/vega/vega-lite",
    stars: 8400,
    contributors: 90,
    daysSinceLastRelease: 14,
    relatedTo: ["29", "35", "93", "104"],
    category: "chart-libraries",
  },
  {
    id: "106",
    name: "G2Plot",
    quadrant: "assess",
    description: "Interactive and responsive charting library based on G2",
    isNew: true,
    githubLink: "https://github.com/antvis/G2Plot",
    stars: 3200,
    contributors: 60,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "35", "93", "101"],
    category: "chart-libraries",
  },
  {
    id: "107",
    name: "Chartist",
    quadrant: "hold",
    description: "Simple responsive charts with great animation and style inheritance",
    isNew: false,
    githubLink: "https://github.com/chartist-js/chartist",
    stars: 12800,
    contributors: 140,
    daysSinceLastRelease: 365,
    relatedTo: ["29", "35", "93", "94"],
    category: "chart-libraries",
  },

  // Date Libraries
  {
    id: "108",
    name: "date-fns",
    quadrant: "adopt",
    description: "Modern JavaScript date utility library focusing on modularity, performance, and immutability",
    isNew: false,
    githubLink: "https://github.com/date-fns/date-fns",
    stars: 30800,
    contributors: 320,
    daysSinceLastRelease: 14,
    relatedTo: ["29", "35", "109", "110", "111"],
    category: "date-libraries",
  },
  {
    id: "109",
    name: "Moment.js",
    quadrant: "hold",
    description: "Parse, validate, manipulate, and display dates in JavaScript (now in maintenance mode)",
    isNew: false,
    githubLink: "https://github.com/moment/moment",
    stars: 47200,
    contributors: 580,
    daysSinceLastRelease: 180,
    relatedTo: ["29", "35", "108", "110", "111"],
    category: "date-libraries",
  },
  {
    id: "110",
    name: "Day.js",
    quadrant: "adopt",
    description: "Fast 2kB alternative to Moment.js with the same modern API",
    isNew: false,
    githubLink: "https://github.com/iamkun/dayjs",
    stars: 43800,
    contributors: 280,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "35", "108", "109", "111"],
    category: "date-libraries",
  },
  {
    id: "111",
    name: "Luxon",
    quadrant: "trial",
    description: "Library for working with dates and times in JavaScript, built by a Moment.js maintainer",
    isNew: false,
    githubLink: "https://github.com/moment/luxon",
    stars: 13800,
    contributors: 120,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "35", "108", "109", "110"],
    category: "date-libraries",
  },
  {
    id: "112",
    name: "js-joda",
    quadrant: "assess",
    description: "Immutable date and time library for JavaScript inspired by Java's JSR-310",
    isNew: false,
    githubLink: "https://github.com/js-joda/js-joda",
    stars: 1800,
    contributors: 40,
    daysSinceLastRelease: 180,
    relatedTo: ["29", "35", "108", "110", "111"],
    category: "date-libraries",
  },
  {
    id: "113",
    name: "date-io",
    quadrant: "trial",
    description: "Abstraction over common JavaScript date management libraries",
    isNew: false,
    githubLink: "https://github.com/dmtrKovalenko/date-io",
    stars: 980,
    contributors: 30,
    daysSinceLastRelease: 60,
    relatedTo: ["29", "35", "108", "109", "110", "111", "112"],
    category: "date-libraries",
  },
  {
    id: "114",
    name: "React Datepicker",
    quadrant: "adopt",
    description: "Simple and reusable datepicker component for React",
    isNew: false,
    githubLink: "https://github.com/Hacker0x01/react-datepicker",
    stars: 7200,
    contributors: 420,
    daysSinceLastRelease: 14,
    relatedTo: ["1", "9", "29", "108", "110"],
    category: "date-libraries",
  },
  {
    id: "115",
    name: "Flatpickr",
    quadrant: "adopt",
    description: "Lightweight and powerful datetime picker with no dependencies",
    isNew: false,
    githubLink: "https://github.com/flatpickr/flatpickr",
    stars: 15800,
    contributors: 180,
    daysSinceLastRelease: 30,
    relatedTo: ["29", "35", "108", "110"],
    category: "date-libraries",
  },
  {
    id: "116",
    name: "FullCalendar",
    quadrant: "adopt",
    description: "Full-sized drag & drop event calendar for JavaScript",
    isNew: false,
    githubLink: "https://github.com/fullcalendar/fullcalendar",
    stars: 16400,
    contributors: 140,
    daysSinceLastRelease: 7,
    relatedTo: ["29", "35", "108", "110", "114", "115"],
    category: "date-libraries",
  },
  {
    id: "117",
    name: "React Big Calendar",
    quadrant: "trial",
    description: "Calendar component for React applications",
    isNew: false,
    githubLink: "https://github.com/jquense/react-big-calendar",
    stars: 6800,
    contributors: 280,
    daysSinceLastRelease: 30,
    relatedTo: ["1", "9", "29", "108", "110", "114", "116"],
    category: "date-libraries",
  },
  {
    id: "118",
    name: "Vue Calendar",
    quadrant: "trial",
    description: "A calendar and datepicker component for Vue.js",
    isNew: false,
    githubLink: "https://github.com/vuejs/vue-calendar",
    stars: 3200,
    contributors: 60,
    daysSinceLastRelease: 180,
    relatedTo: ["2", "10", "29", "110", "115"],
    category: "date-libraries",
  },
  {
    id: "119",
    name: "Angular Material Datepicker",
    quadrant: "adopt",
    description: "Datepicker component from the Angular Material library",
    isNew: false,
    githubLink: "https://github.com/angular/components",
    stars: 23800,
    contributors: 580,
    daysSinceLastRelease: 7,
    relatedTo: ["3", "29", "108", "110"],
    category: "date-libraries",
  },
]

const TechRadarContext = createContext<TechRadarContextType | undefined>(undefined)

export function TechRadarProvider({ children }: { children: React.ReactNode }) {
  const [items, setItems] = useState<TechItem[]>(defaultItems)
  const [selectedItem, setSelectedItem] = useState<TechItem | null>(null)
  const [filteredQuadrant, setFilteredQuadrant] = useState<Quadrant | "all">("all")
  const [filteredCategories, setFilteredCategories] = useState<string[]>([])
  const [searchTerm, setSearchTerm] = useState<string>("")
  const [filteredItems, setFilteredItems] = useState<TechItem[]>(items)
  const [showModal, setShowModal] = useState<boolean>(false)
  const [showRelations, setShowRelations] = useState<boolean>(false)
  const [starsRange, setStarsRange] = useState<[number, number]>([0, Math.max(...items.map((item) => item.stars || 0))])
  const [contributorsRange, setContributorsRange] = useState<[number, number]>([
    0,
    Math.max(...items.map((item) => item.contributors || 0)),
  ])
  const [daysRange, setDaysRange] = useState<[number, number]>([
    0,
    Math.max(...items.map((item) => item.daysSinceLastRelease || 0)),
  ])
  const [searchIn, setSearchIn] = useState<"all" | "name" | "description">("all")
  const [viewMode, setViewMode] = useState<"radar" | "table">("radar")

  // Update filtered items whenever filters or search term changes
  useEffect(() => {
    const newFilteredItems = items.filter((item) => {
      const matchesQuadrant = filteredQuadrant === "all" || item.quadrant === filteredQuadrant

      // Category filtering - only apply if there are selected categories
      const matchesCategory = filteredCategories.length === 0 || filteredCategories.includes(item.category || "")

      // Search term filtering
      let matchesSearch = true
      if (searchTerm !== "") {
        if (searchIn === "name") {
          matchesSearch = item.name.toLowerCase().includes(searchTerm.toLowerCase())
        } else if (searchIn === "description") {
          matchesSearch = item.description.toLowerCase().includes(searchTerm.toLowerCase())
        } else {
          matchesSearch =
            item.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
            item.description.toLowerCase().includes(searchTerm.toLowerCase())
        }
      }

      // Advanced filters

      // Filter by stars range
      if ((item.stars || 0) < starsRange[0] || (item.stars || 0) > starsRange[1]) return false

      // Filter by contributors range
      if ((item.contributors || 0) < contributorsRange[0] || (item.contributors || 0) > contributorsRange[1])
        return false

      // Filter by days since last release range
      if ((item.daysSinceLastRelease || 0) < daysRange[0] || (item.daysSinceLastRelease || 0) > daysRange[1])
        return false

      return matchesQuadrant && matchesCategory && matchesSearch
    })

    setFilteredItems(newFilteredItems)
  }, [items, filteredQuadrant, filteredCategories, searchTerm, starsRange, contributorsRange, daysRange, searchIn])

  const addItem = (item: Omit<TechItem, "id">) => {
    const newItem = {
      ...item,
      id: Math.random().toString(36).substring(2, 9),
    }
    setItems((prev) => [...prev, newItem])
  }

  const removeItem = (id: string) => {
    setItems((prev) => prev.filter((item) => item.id !== id))
    if (selectedItem?.id === id) {
      setSelectedItem(null)
    }
  }

  const updateItem = (id: string, updatedItem: Partial<TechItem>) => {
    setItems((prev) => prev.map((item) => (item.id === id ? { ...item, ...updatedItem } : item)))
    if (selectedItem?.id === id) {
      setSelectedItem((prev) => (prev ? { ...prev, ...updatedItem } : null))
    }
  }

  return (
    <TechRadarContext.Provider
      value={{
        items,
        filteredItems,
        addItem,
        removeItem,
        updateItem,
        selectedItem,
        setSelectedItem,
        filteredQuadrant,
        setFilteredQuadrant,
        filteredCategories,
        setFilteredCategories,
        searchTerm,
        setSearchTerm,
        showModal,
        setShowModal,
        showRelations,
        setShowRelations,
        starsRange,
        setStarsRange,
        contributorsRange,
        setContributorsRange,
        daysRange,
        setDaysRange,
        searchIn,
        setSearchIn,
        viewMode,
        setViewMode,
      }}
    >
      {children}
    </TechRadarContext.Provider>
  )
}

export function useTechRadar() {
  const context = useContext(TechRadarContext)
  if (context === undefined) {
    throw new Error("useTechRadar must be used within a TechRadarProvider")
  }
  return context
}

